In [1]:
class Employee:

    employee_count = 0

    def __init__(self, name, family, salary, department):
        self.name = name
        self.family = family
        self.salary = salary
        self.department = department
        Employee.employee_count += 1

    @classmethod
    def calculate_average_salary(cls, employee_list):
        total_salary = sum(employee.salary for employee in employee_list)
        if cls.employee_count>0:
          return total_salary / cls.employee_count
        else:
          return 0

class FulltimeEmployee(Employee):
    def __init__(self, name, family, salary, department):
        super().__init__(name, family, salary, department)


employees = [
    Employee("Alice", "Smith", 70000, "Engineering"),
    FulltimeEmployee("Bob", "Johnson", 80000, "Marketing"),
    Employee("Charlie", "Brown", 80000, "Sales")
]

average_salary = Employee.calculate_average_salary(employees)
print("Average Salary:", average_salary)


Average Salary: 76666.66666666667


In [2]:
pip install numpy


In [3]:
import numpy as np

random_vector = np.random.uniform(1, 20, 20)

matrix = random_vector.reshape(4, 5)
print("Original Matrix:")
print(matrix)

max_indices = matrix.argmax(axis=1)

matrix[np.arange(matrix.shape[0]), max_indices] = 0

print("Modified Matrix:")
print(matrix)


Original Matrix:
[[ 6.10938624 13.50944185 19.22976065 17.1348619  19.58077813]
 [11.20317189  7.69489277  7.79185012  2.11832887  1.00043612]
 [ 9.30550196  1.44009174  4.90654579  9.56752652 18.14842501]
 [16.56261438 17.08687366  6.23283737 17.05049358 10.64944069]]
Modified Matrix:
[[ 6.10938624 13.50944185 19.22976065 17.1348619   0.        ]
 [ 0.          7.69489277  7.79185012  2.11832887  1.00043612]
 [ 9.30550196  1.44009174  4.90654579  9.56752652  0.        ]
 [16.56261438  0.          6.23283737 17.05049358 10.64944069]]
